source /media/data/Github/user_defined_functions
postgres "alter table hn_stories add column descendants int"
postgres "alter table hn_stories add column id int"
postgres "alter table hn_stories add column kids int[]"
postgres "alter table hn_stories add column score int"
postgres "alter table hn_stories add column time int"
postgres "alter table hn_stories add column title varchar(300)"
postgres "alter table hn_stories add column type varchar(80)"
postgres "alter table hn_stories add column url varchar(200)"
postgres "alter table hn_stories add column url varchar(300)"
postgres "alter table hn_stories alter column url type varchar(300)"
postgres "alter table hn_stories add column dead boolean"
postgres "alter table hn_stories add column deleted boolean"
postgres "alter table hn_stories add column descendants int"
postgres "alter table hn_stories add column parent int"
postgres "alter table hn_stories add column text text"
postgres "alter table hn_stories add constraint constraint_name unique (id)"
postgres "alter table hn_stories add constraint unique (id)"
postgres "alter table hn_stories add constraint constraint_name unique (id)"
postgres "alter table hn_stories add constraint unique_ids unique (id)"
postgres "alter table hn_stories add column url_domain text"
postgres "alter table hn_stories add column url_domain_count int"
